### ISSUE TITLE
Get the DSLR to Interact with the Raspberry Pi

### ISSUE THREAD

**Issue by jrcharlo** [jpschnel/maze-vision#5]
The DSLR does not interact with the Raspberry Pi properly, this needs to be fixed so that gphoto2 can take pictures.

**Comment by jpschnel** [comment]
Got it, turns out we need to remove the sd card from the DSLR before connecting it to the Raspberry Pi for it to take pictures.

**Comment by nwhahn** [comment]
Also the code is now with the Maze_vision.py document
