### ISSUE TITLE
Development Branch

### ISSUE THREAD

**Issue by jrcharlo** [jpschnel/maze-vision#6]
Rename V0.1.0 (or whatever it is currently named) to "development" so that we have a development branch. Everybody (all 4 team members) must have their own local feature branch which must be pushed to development by Monday (Sprint 1 date) and then Master must be pushed/updated to V0.2.0.

**Comment by nwhahn** [comment]
I set up the major feature branches as well as fixing the development branch a few days ago, forgot to close this.
